const CONFIG = {
    appProducer: "CYBEARL",
    appName: "G.E.N.E.S.I.S.",
    appVersion: "DE.GV 1.0.0",
    appDescription: `
        A TRADING BOT MADE BY CYBEARL. WORKING ON SHORT TIMEFRAME. MAKING PROFITS WITH SMALL RISK.
        USING A POOL OF WEIGHTED STRATEGIES. ENTIRELY DEVELOPED BY YORATONI <3
    `,
    appDisclaimer: `
        THIS SOFTWARE IS FOR EDUCATIONAL PURPOSES ONLY. DO NOT RISK MONEY WHICH YOU ARE AFRAID TO LOSE.
        USE THE SOFTWARE AT YOUR OWN RISK. THE AUTHORS ASSUME NO RESPONSIBILITY FOR YOUR TRADING RESULTS.
    `,

    isDebug: true,

    nav: {
        reducedSize: 64,
        expandedSize: 200
    }
};

export default CONFIG;