export const generateHelpMsg = `
Usage: yarn generate [options]

Description
    This system is used to generate the data needed by the HSS to calculate the score of a strategy.
    It generates a JSON file containing the data of the market for each candle over a period of time.

    The file is named after the different parameters used to generate it
    which allows querying the data by the same parameters in the HSS.

Options
    --help              Display this message.
    --tradingPair       The trading pair to generate the data for.
                        Defaults to 'BNB/USDT'.
    --timeframe         The timeframe to generate the data for.
                        Defaults to '1m'.
    --duration          The duration of the data to generate,
                        represented as a timeframe, such as 30s, 1m, 1h, 4d, etc.
                        Defaults to '1h'.
    --entriesPerPage    The amount of entries per page.
                        Defaults & limited to 512 entries.
`;

export const scoreHelpMsg = `
Usage: yarn score [options]

Description
    This system is used to calculate the score of a strategy based on its performance on historical data.

    The historical data is generated by the generate system and is stored in the 'pipes/data' folder.

    The HSS will generate, under 'pipes/scores', a folder for each strategy (named by the strategy name),
    containing a 'score.json' file for the latest score, and a reports subdirectory containing the reports
    for each run (named by date) containing graphics and data for analysis.

Options
    --help              Display this message.
    --show              Displays the data currently available with the filters applied.
    --showAll           Can be used to display the available data for scoring.
    --tradingPair       The trading pair to generate the data for.
                        Defaults to 'ALL'.
    --base              The base currency to generate the data for.
                        Defaults to 'ALL'.
    --quote             The quote currency to generate the data for.
                        Defaults to 'ALL'.
    --timeframe         The timeframe to generate the data for.
                        Defaults to 'ALL'.
    --minDuration       The minimum duration of the data to use, represented as a timeframe,
                        such as 30s, 1m, 1h, 4d, etc.
                        Defaults to 'ALL'.
`;