appId: com.cybearl.genesis
productName: Genesis
copyright: Copyright © 2023 Cybearl
directories:
  output: dist
  buildResources: resources
files:
  - from: .
    filter:
      - package.json
      - app
publish: null
